
package com.example.integrationservice.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "OrderStatusPort", targetNamespace = "http://soapservice.com/soapentity")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderStatusPort {


    /**
     * 
     * @param orderStatusRequest
     * @return
     *     returns com.test.integrationservice.wsdl.OrderStatusResponse
     */
    @WebMethod(operationName = "OrderStatus")
    @WebResult(name = "OrderStatusResponse", targetNamespace = "http://soapservice.com/soapentity", partName = "OrderStatusResponse")
    public OrderStatusResponse orderStatus(
        @WebParam(name = "OrderStatusRequest", targetNamespace = "http://soapservice.com/soapentity", partName = "OrderStatusRequest")
        OrderStatusRequest orderStatusRequest);

}
